
TARGET         = breakout_32u2
TARGET_PATH    = ./breakout_32u2
PARENT_PATH    = ./..
MCU            = atmega32u2
F_CPU          = 8000000
LWCLONE_SRC    = ../main_usb.c ../descriptors.c ../comm.c ../led.c ../panel.c ../queue.c

include ../lufa.mk
