
MCU          = atmega328
F_CPU        = 16000000
TARGET       = arduino_uno__m328
LWCLONE_SRC  = ../../main_led.c ../../comm.c ../../led.c ../../panel.c ../../queue.c ../../clock.c

include ../../default.mk
