
TARGET         = arduino_leonardo
TARGET_PATH    = ./arduino_leonardo
PARENT_PATH    = ./..
MCU            = atmega32u4
F_CPU          = 16000000
LWCLONE_SRC    = ../main_usb.c ../descriptors.c ../comm.c ../led.c ../queue.c

include ../lufa.mk
