
TARGET         = arduino_promicro
TARGET_PATH    = ./arduino_promicro
PARENT_PATH    = ./..
MCU            = atmega32u4
F_CPU          = 16000000
LWCLONE_SRC    = ../main_usb.c ../descriptors.c ../comm.c ../led.c ../panel.c ../queue.c ../clock.c

include ../lufa.mk
