
TARGET         = arduino_uno__m8u2
TARGET_PATH    = ./arduino_uno/m8u2
PARENT_PATH    = ../..
MCU            = atmega8u2
F_CPU          = 16000000
LWCLONE_SRC    = ../../main_usb.c ../../descriptors.c ../../comm.c ../../led.c ../../panel.c ../../queue.c ../../clock.c
CFLAGS         = -I./.

include ../../lufa.mk
