
TARGET         = arduino_mega2560__m16u2
TARGET_PATH    = ./arduino_mega2560/m16u2
PARENT_PATH    = ../..
MCU            = atmega16u2
F_CPU          = 16000000
LWCLONE_SRC    = ../../main_usb.c ../../descriptors.c ../../comm.c ../../led.c ../../queue.c
CFLAGS         = -I./.

include ../../lufa.mk
