
MCU          = atmega2560
F_CPU        = 16000000
TARGET       = arduino_mega2560__m2560
LWCLONE_SRC  = ../../main_led.c ../../comm.c ../../led.c ../../panel.c ../../queue.c

include ../../default.mk
